version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.7
artifacts:
  files:
    -  README.md
    -  application.py
    -  requirements.txt
    -  files/CCC.pickle
    -  files/Fraud_detection.pickle
    -  files/forecast_sales.pickle
    -  files/senti_predi.pickle
    -  files/train.csv
eb_codebuild_settings:
  CodeBuildServiceRole: AWSCodePipelineServiceRole-us-east-1-dashpipe
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/standard:2.0
  Timeout: 60
      
